# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:943cuoomDG8PTtu0pqY=,iv:zYbxM0tWv4rndO8BEOKM1en5lEJRVAXpnDzVanXqCo4=,tag:1Q8c51HXqtbBKB2WrWij4g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:edMwrqW7HGqhbx0cUI3GGqL/Dbk=,iv:shV33kiZKG3yO+5HBCMPNxgZQQhLOgjWV/Bi3an+444=,tag:USkNY08IcS1cMIa6VTYw9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2xcuzlxvt4rnegyr7ja9z0nn9d3tclm60dqkcr9khsrarqaeufq2jexu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNalRuRjdIeEJmUlpKbWIr
            SHEvY1VCVFh6dGN6cnZsWFVGdGhHSFh0S0hJCmNhK3VhZVRIdyt0am5aNTgxRnBR
            eWVpVzJWdWFiem1xOGRPcVhQdEcwWmcKLS0tIFN2VmJFZjdGU0ZTUmJwcnRMSmt1
            UUVSMTZYZ3I2NGRTZWxFa2t2M2R1SlEKV24CluSBclGI0br7ph/w2pAPCaFOa8sT
            r+FM/rloYiWQTySsVqHQobveod0g2S2x1YzvFx8mMIXAifRrU4lVfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T13:24:28Z"
    mac: ENC[AES256_GCM,data:Pvf332lk/QL+FLYL0G/+/4p+Z4b+9YOTj0ZCzZnW4HhsFfkwwuk6WOfEvrAS4F7J91Zd5AI6itDVgk83wX/9jENt5ldPrZtqa8jJZCXVKGlXUl4QVTq9gI0EYLYo0yqlz2w/m41g3CL4i7pOHXfA6AoBlzZSmtyJelXzIhuU9rw=,iv:ff6irNPfvrh/vbPDOfhSko2eQih38fEr+OpLP7U3xaU=,tag:FPDty8Nil11ZBc2mDbddRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
