# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:F9+uqBbsW0c26Y6/uePnKp6Exu4bf8k83loIkpJP6vwKIzGxpg==,iv:EBFIvrYWitZfqiH7PR/nputOutrnqmRNQRRhOwnDnig=,tag:20Tl4O1bbNTykfJHyfrFOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2xcuzlxvt4rnegyr7ja9z0nn9d3tclm60dqkcr9khsrarqaeufq2jexu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRS002SDROQUtUNHN4RWRj
            WnlzeHRkWk5mWncremdIYTZjakd2MndBd3pZCjhETGZEb1N2S2w1aFREZjJ4b3Nq
            VC9LTE1UVU9QcFhJSlV3eEJQbDJwNkUKLS0tIFlnUC9YdFozQ3QzWjhIQ0NHQkkz
            bkppMGQ1RjVzSzI4ekRPSm0ydDI5STQKg85P1obydnBHMZLGvh+uHFcaiTz4xDD7
            BjWXldwvqv4pknNKXsLO9BD+zfx8RefZHXk9+f4XOtM+GqJH1VpPRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-03T13:24:28Z"
    mac: ENC[AES256_GCM,data:9Dm1lF2gGCTdiqSpzjRAVK7/UH/DLmpFknUC8+rTYabRWrIIyWBvTRFIOWsAMOdNCZotah/1wpr+kso0EHGGqB70vAAotvJAp3za3cVJ8E1flCjV2c0C0tutJpU0LV5NWRbR0Mey6gUdYqXvjgdGkeur4+zJHz/nroQrOKO4deg=,iv:TKV62cL78RFGi/YuLzOzb1xddOSxyUcu635XeQzDX3k=,tag:5phjiktFFfeyGXBrIDW4Dw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
